export const artworks = [
  {
    id: "1",
    title: "Al Ritmo de la Mirada Interior",
    year: "2022",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$125,000",
    image: "/artwork-1.jpg",
    height: 400,
    sold: false,
    medium: "Painting",
    rarity: "Unique",
    dimensions: "120x80cm",
    seller: "Harper's Gallery",
  },
  {
    id: "2",
    title: "Volver con la Misma Fortaleza",
    year: "2022",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$35,000",
    image: "/artwork-2.jpg",
    height: 500,
    sold: true,
    medium: "Painting",
    rarity: "Unique",
    dimensions: "100x70cm",
    seller: "Harper's Gallery",
  },
  {
    id: "3",
    title: "La danza",
    year: "2022",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$85,000",
    image: "/artwork-3.jpg",
    height: 600,
    sold: false,
    medium: "Painting",
    rarity: "Unique",
    dimensions: "110x90cm",
    seller: "Harper's Gallery",
  },
  {
    id: "4",
    title: "Memoria Ancestral",
    year: "2022",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$55,000",
    image: "/artwork-4.jpg",
    height: 350,
    sold: false,
    medium: "Mixed Media",
    rarity: "Limited Edition",
    dimensions: "90x60cm",
    seller: "Harper's Gallery",
  },
  {
    id: "5",
    title: "Espíritu de la Selva",
    year: "2021",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$100,000",
    image: "/artwork-5.jpg",
    height: 450,
    sold: true,
    medium: "Painting",
    rarity: "Unique",
    dimensions: "130x100cm",
    seller: "Harper's Gallery",
  },
  {
    id: "6",
    title: "Raíces del Tiempo",
    year: "2021",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$65,000",
    image: "/artwork-6.jpg",
    height: 380,
    sold: false,
    medium: "Painting",
    rarity: "Unique",
    dimensions: "95x75cm",
    seller: "Harper's Gallery",
  },
  {
    id: "7",
    title: "Cosmos Interior",
    year: "2023",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$110,000",
    image: "/artwork-1.jpg",
    height: 520,
    sold: false,
    medium: "Painting",
    rarity: "Unique",
    dimensions: "140x110cm",
    seller: "Harper's Gallery",
  },
  {
    id: "8",
    title: "Territorio Sagrado",
    year: "2023",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$75,000",
    image: "/artwork-2.jpg",
    height: 420,
    sold: false,
    medium: "Mixed Media",
    rarity: "Limited Edition",
    dimensions: "120x90cm",
    seller: "Harper's Gallery",
  },
  {
    id: "9",
    title: "Visión Chamánica",
    year: "2023",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$95,000",
    image: "/artwork-3.jpg",
    height: 480,
    sold: false,
    medium: "Painting",
    rarity: "Unique",
    dimensions: "115x85cm",
    seller: "Harper's Gallery",
  },
  {
    id: "10",
    title: "Río de Colores",
    year: "2022",
    artist: "Carlos Jacanamijoy",
    gallery: "Harper's",
    price: "US$68,000",
    image: "/artwork-4.jpg",
    height: 360,
    sold: true,
    medium: "Painting",
    rarity: "Unique",
    dimensions: "105x80cm",
    seller: "Harper's Gallery",
  },
];
